name: PandeLoot
main: net.seyarada.pandeloot.PandeLoot
version: 0.2.0-beta
api-version: 1.13
softdepend: [MythicMobs, MythicArtifacts, PlaceholderAPI, Vault, HoloBroadcast, MMOItems, MMOCore, Oraxen, DiscordSRV, Denizen, Citizens, Citizens2, CitizensAPI ]
commands:aa
  pandeloot:
    description: Your description
    usage: /pandeloot
    permission: pandeloot.use